const DataCardCar = [
                    {
                                        URLimage: "images/Mg4.png",
                                        mainmodel: "MG4",
                                        detail1: "Grade: X / 969,000",
                                        detail2: "Grade: D / 869,000",
                                        detail3: "",
                                        detail4: "",
                                        detail5: "",
                    },
                    {
                                        URLimage: "images/mgmaxus9detail.png",
                                        mainmodel: "Coming Soon",
                                        detail1: "",
                                        detail2: "",
                                        detail3: "",
                                        detail4: "",
                                        detail5: "",
                    },
                    {
                                        URLimage: "images/mgesdetail.png",
                                        mainmodel: "Coming Soon",
                                        detail1: "",
                                        detail2: "",
                                        detail3: "",
                                        detail4: "",
                                        detail5: "",
                    },
                    {
                                        URLimage: "images/Newmgzs.png",
                                        mainmodel: "MG ZS 1.5 (MY2022)",
                                        detail1: "Grade: V / 799,000",
                                        detail2: "Grade: X / 709,000",
                                        detail3: "Grade: D / 625,000",
                                        detail4: "",
                                        detail5: "",
                    },
                    {
                                        URLimage: "images/Newmgextenderdc.png",
                                        mainmodel: "MG5 1.5 (MY2022)",
                                        detail1: "Grade: X / 709,000",
                                        detail2: "Grade: D+ / 679,000",
                                        detail3: "Grade: D / 625,000",
                                        detail4: "Grade: C / 585,000",
                                        detail5: "",
                    },
                    {
                                        URLimage: "images/Newmg5.png",
                                        mainmodel: "MG5 1.5 (MY2022)",
                                        detail1: "Grade: X / 709,000",
                                        detail2: "Grade: D+ / 679,000",
                                        detail3: "Grade: D / 625,000",
                                        detail4: "Grade: C / 585,000",
                                        detail5: "",
                    },
                    {
                                        URLimage: "images/Newmgep.png",
                                        mainmodel: "MG EP",
                                        detail1: "Grade: EP+ / 771,000",
                                        detail2: "",
                                        detail3: "",
                                        detail4: "",
                                        detail5: "",
                    },
                    {
                                        URLimage: "images/Newmgvshev.png",
                                        mainmodel: "MG VS HEV",
                                        detail1: "Grade: X (TWO TONE) / 929,000",
                                        detail2: "Grade:  X (MONO TONE) / 919,000",
                                        detail3: "Grade: D / 859,000",
                                        detail4: "",
                                        detail5: "",
                    },
                    {
                                        URLimage: "images/Newmghs.png",
                                        mainmodel: "MG HS 1.5 (MCE 2022)",
                                        detail1: "Grade: X / 1,159,000",
                                        detail2: "Grade: D / 1,089,000",
                                        detail3: "Grade: C / 939,000",
                                        detail4: "",
                                        detail5: "",
                    },
];
export default DataCardCar;